### ISSUE TITLE
牛客和atc好像失效了

### ISSUE THREAD

**Issue by nXhp98** [HuParry/nonebot-plugin-cp-broadcast#4]
cf正常  牛客atc都提示  突然出错了，稍后再试哦~

**Comment by HuParry** [comment]
atc我自己测试是没问题的。牛客是因为到了月底，牛客竞赛日历列表为空，因此误判断为错了。等到3月初发送牛客就会有信息。

atc的话考虑一下网络问题？毕竟是从日本网站爬取。

牛客功能我再更改一下逻辑，这个问题我之前就发现了，没来得及更改，今天下午应该会改好。

**Comment by nXhp98** [comment]
![mmexport1707969752583](https://github.com/HuParry/nonebot-plugin-cp-broadcast/assets/50262595/6db9b5db-8ba5-4590-94ac-33f7db88acc2)

**Comment by HuParry** [comment]
你好，问题已经修复，你直接更新插件即可。

![IMG_5997](https://github.com/HuParry/nonebot-plugin-cp-broadcast/assets/103566602/4eddfdf6-9cdb-469c-b520-ce12ca2f6b71)
